name: A pull workflow 
on: pull_request
jobs:
  build:
    name: Pull hello world actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-pull
        with:
          MY_NAME: "Shivam_Verma"
